vich_uploader:
    db_driver: orm
    mappings:
        model_images:
            uri_prefix: /uploads/images/models
            upload_destination: '%kernel.project_dir%/public/uploads/images/models'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        attachments:
            uri_prefix: /uploads/images/modelsAttachments
            upload_destination: '%kernel.project_dir%/public/uploads/images/modelsAttachments'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
